### ISSUE TITLE
error: failed to solve: no match for platform in manifest when using multi-stage builds

### ISSUE THREAD

**Issue by n-i-x** [crazy-max/goxx#38]
I've got a node.js frontend that I serve with a go daemon that handles a REST API. I discovered this project because I need to have this daemon work on OSX and goxx does a fantastic job of compiling my CGO app for all the supported platforms. The issue is trying to incorporate the node.js build into goxx.

Here are the relevant bits from my Dockerfile:

```
ARG GOXX_BASE
ARG GOBUILDTYPE
FROM node:latest as node-build

WORKDIR /base
COPY pixelweb/companion/package.json .
COPY pixelweb/companion/yarn.lock .
RUN --mount=type=bind,source=. \
  cd pixelweb/companion && yarn install
RUN --mount=type=bind,source=. \
  cd pixelweb/companion && yarn build
```

When trying to build, I now get the following error:

```
 => CANCELED [linux/amd64 internal] load metadata for docker.io/crazymax/goxx:latest                                                                                           0.1s
 => ERROR [windows/amd64 internal] load metadata for docker.io/library/node:latest                                                                                             0.1s
 => CANCELED [linux/amd64 internal] load metadata for docker.io/crazymax/osxcross:11.3                                                                                         0.1s
 => CANCELED [windows/386 internal] load metadata for docker.io/library/node:latest                                                                                            0.1s
------
 > [windows/amd64 internal] load metadata for docker.io/library/node:latest:
------
Dockerfile:4
--------------------
   2 |     ARG GOXX_BASE
   3 |     ARG GOBUILDTYPE
   4 | >>> FROM node:latest as node-build
   5 |
   6 |     WORKDIR /base
--------------------
error: failed to solve: no match for platform in manifest sha256:ad3314b09371eb7f085c689ab2a3b00e41362cbc20e98bfaa27a9eaf78abd2a8: not found
```

I'm assuming this is because goxx is trying to select a node container matching the target platform? This issue is preventing the project from moving fully to goxx. I currently have to run `yarn install && yarn build` in another container and then build the CGO app using the already built node.js app.

**Comment by n-i-x** [comment]
Is this project dead?

**Comment by crazy-max** [comment]
> `=> ERROR [windows/amd64 internal] load metadata for docker.io/library/node:latest`

`node:latest` does not support `windows/amd64` platform yes. You have to enforce the build platform using the `$BUILDPLATFORM` arg from global scope as shown in https://github.com/crazy-max/goxx#usage.

But I don't see anything related to building a Go project. Also `node:latest` image does not have any Go runtime afaik.

**Comment by saschasc** [comment]
Thanks for the fix. Current main works now. Awesome!
