### ISSUE TITLE
[doc][enhancement] Add windows Arm support in doc

### ISSUE THREAD

**Issue by PhenixH** [crazy-max/goxx#45]
Hi, 

Great work ! and thanks for sharing :) 

I saw that windows arm is supported (and I tested windows/arm64), but the readme do not offer this precision.

**Suggestion :** 
update readme to include windows arm support 

Many thanks 👍

**Comment by crazy-max** [comment]
> I saw that windows arm is supported (and I tested windows/arm64),

There is no cross pkg for `mingw-w64-aarch64` available atm afaik. Guess it works for you because your project doesn't require Cgo.
