### ISSUE TITLE
Any reason to remove git?

### ISSUE THREAD

**Issue by pratikbalar** [crazy-max/goxx#6]

**Comment by pratikbalar** [comment]
Ahh, I got it, Git is `goreleaser-xx`'s dep, not `goxx`'s. 

Thanks for all amazing projects

---

**May the Source Be With You**

**Comment by crazy-max** [comment]
@pratikbalar Yes I should have stipulated that in the latest release notes linked to https://github.com/crazy-max/goxx/pull/4/files. The idea behind it was to drastically reduce the image size. Previously ~2.8GB and now ~450MB.

> Thanks for all amazing projects

You're welcome, thanks for testing this project!

**Comment by pratikbalar** [comment]
> The idea behind it was to drastically reduce the image size. Previously ~2.8GB and now ~450MB.

That's cool.

Actually removing `git` that broke one of my `goreleaser-xx` based CI so

**Comment by pratikbalar** [comment]
Thank you for inspiring me every day for open source,

**Comment by crazy-max** [comment]
> > The idea behind it was to drastically reduce the image size. Previously ~2.8GB and now ~450MB.
> 
> That's cool.
> 
> Actually removing `git` that broke one of my `goreleaser-xx` based CI so

If you're using `goreleaser-xx` with `goxx`, I have updated the documentation to fix the `git` issue. See https://github.com/crazy-max/goreleaser-xx#crazy-maxgoxx
